### ISSUE TITLE
How do I install it in Ubuntu 16.04 (64bit) platform?

### ISSUE THREAD

**Issue by OutGazing** [naokij/go-hosts-updater#2]

**Comment by naokij** [comment]
在[releases](https://github.com/naokij/go-hosts-updater/releases)里下载go-hosts-updater_linux_amd64，直接执行即可

**Comment by OutGazing** [comment]
The version for windows works well, yet the *linux_amd64 doesn't. "Main.go"
 seems lack of path contents.

**Comment by naokij** [comment]
在Ubuntu 14.04.5 LTS 64位下测试是OK的，我会在你说的版本下面再测试看看。

**Comment by naokij** [comment]
测试Ubuntu 16.04.2 LTS 64位也正常
