### ISSUE TITLE
win10 专业版 X64 似乎不能用，还是我的使用方法不对？？

### ISSUE THREAD

**Issue by littledaoying** [naokij/go-hosts-updater#6]
我的系统是 WIN10 专业版 1703，15063.413，X64，
我下载的 win10的exe文件，
我试了6种情况，即 分别把exe文件放在 桌面，hosts的同文件夹，D盘的某个位置，然后分别用 普通双击 和管理员权限 运行。
这6种情况都是闪了一下黑框，不能更新hosts。

请问，是哪里的问题，还是我使用方法不对？？谢谢！！

**Comment by naokij** [comment]
我需要找一个win10测试看看

**Comment by naokij** [comment]
或者你开一个管理员权限的CMD，在cmd里面运行go-hosts-updater_windows_amd64.exe，然后把报错信息贴上来

**Comment by CharleVV** [comment]
最新版的下载不了

**Comment by littledaoying** [comment]
@Pesdestrian  挂VPN就能下载了。。。。

**Comment by naokij** [comment]
@Pesdestrian 某墙对github一直不友好😓
